# Generated by Django 3.0.4 on 2020-04-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'meals'},
        ),
        migrations.AddField(
            model_name='meals',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='people',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='meals',
            name='preperation_time',
            field=models.CharField(max_length=120),
        ),
    ]
